#!/usr/bin/env bash
# PreToolUse: Thumbmix.xcodeproj is generated by xcodegen and git-ignored, so an edit there is lost.
file=$(plutil -extract tool_input.file_path raw -o - - 2> /dev/null) || exit 0
case "$file" in
  *.xcodeproj/* | *.xcodeproj)
    echo "Thumbmix.xcodeproj is generated: edit project.yml, then run xcodegen generate." >&2
    exit 2
    ;;
esac
